# Generated by Django 4.0.1 on 2022-01-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
