version: '4.4.4'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python app.py'
    ports:
      - 8002:5000
    volumes:
      - .:/app
    depends_on:
      - db
  

  rabbitmq:
    image: rabbitmq
    volumes:
      - ./etc/rabbitmq/conf:/etc/rabbitmq/
      - ./etc/rabbitmq/data/:/var/lib/rabbitmq/
      - ./etc/rabbitmq/logs/:/var/log/rabbitmq/
    command: rabbitmq-server
    expose:
      - 5672 #amqp
      - 15672 #http
    healthcheck:
        test: [ "CMD", "rabbitmqctl", "status"]
        interval: 5s
        timeout: 20s
        retries: 5
          

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db, backend, rabbitmq
  
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_DB: dj

    volumes:
      - .dbdata:/var/lib/postgres/data\
    ports:
      - 33068:5432